# Generated by Django 5.2.4 on 2025-07-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('context', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=40)),
                ('context', models.TextField(blank=True)),
                ('updated_ed', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.region')),
            ],
        ),
        migrations.CreateModel(
            name='mahalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ed', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=40)),
                ('context', models.TextField(blank=True)),
                ('updated_ed', models.DateTimeField(auto_now=True)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tuman')),
            ],
        ),
    ]
