# Generated by Django 5.2.4 on 2025-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='created_ed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tuman',
            name='created_ed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
